require("dotenv").config();

module.exports = {
  PORT: process.env.PORT,
  DB_NAME: process.env.DB_NAME,
  DB_USER: process.env.DB_USER,
  DB_PASS: process.env.DB_PASS,
  SECRET: process.env.SECRET,
  MAIL_HOST: process.env.MAIL_HOST,
  MAIL_PORT: process.env.MAIL_PORT,
  MAIL_USER: process.env.MAIL_USER,
  MAIL_PASS: process.env.MAIL_PASS,
  XUM_KEY: process.env.XUM_KEY,
  XUM_SECRET: process.env.XUM_SECRET,
  cloud_name: process.env.cloud_name,
  api_key: process.env.api_key,
  api_secret: process.env.api_secret,
  dev_net_xrpl: process.env.dev_net_xrpl,
  PINATA_API_KEY: process.env.PINATA_API_KEY,
  PINATA_API_SECRET: process.env.PINATA_API_SECRET,
  PINATA_JWT: process.env.PINATA_JWT,
  PINATA_API_URL: process.env.PINATA_API_URL,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
  dev_net_xrpl_nft: process.env.dev_net_xrpl_nft,
  dev_net_xrpl_nft_xumm: process.env.dev_net_xrpl_nft_xumm,
};
